In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
import sys
!{sys.executable} -m pip install --user tensorflow

In [3]:
df = pd.read_csv("insurance.csv")

df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [4]:
df.isna().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [6]:
encoder = LabelEncoder()

df["sex"] = encoder.fit_transform(df["sex"])

df["smoker"] = encoder.fit_transform(df["smoker"])

df["region"] = encoder.fit_transform(df["region"])

In [7]:
df.head()

   age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       3  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       1  21984.47061
4   32    1  28.880         0       0       1   3866.85520

In [8]:
X = df.drop("charges", axis=1)

y = df["charges"]

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [10]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [11]:
model = Sequential()

model.add(Dense(64, activation="relu", input_shape=(X_train.shape[1],)))

model.add(Dense(32, activation="relu"))

model.add(Dense(16, activation="relu"))

model.add(Dense(1))

C:\Users\itsme\AppData\Roaming\Python\Python313\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [13]:
model.compile(optimizer="adam",loss="mse",metrics=["mae"])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [14]:
history = model.fit(X_train,y_train,epochs=100,batch_size=32,validation_split=0.2)

Epoch 1/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - loss: 325453312.0000 - mae: 13518.0674 - val_loss: 310332256.0000 - val_mae: 12654.2783
Epoch 2/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 325402176.0000 - mae: 13516.3037 - val_loss: 310246688.0000 - val_mae: 12651.2402
Epoch 3/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 325242816.0000 - mae: 13511.0928 - val_loss: 310000768.0000 - val_mae: 12642.8291
Epoch 4/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 324817216.0000 - mae: 13497.6123 - val_loss: 309372608.0000 - val_mae: 12622.1738
Epoch 5/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 323795296.0000 - mae: 13466.5479 - val_loss: 307988032.0000 - val_mae: 12578.1660
Epoch 6/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 321670784.0000 - mae: 13402.8672 - val_loss: 305192128.0000 - val_mae: 12492.6533
Epoch 7/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 317807840.0000 - mae: 13287.1133 - val_loss: 300252672.0000 - val_mae: 12345.9473
Epoch 8/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 310920448.0000 - mae: 13096.0186 - val_loss: 292370048.0000 - val_mae: 12114.9600
Epoch 9/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 300505664.0000 - mae: 12794.5537 - val_loss: 280150048.0000 - val_mae: 11762.1484
Epoch 10/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 284659424.0000 - mae: 12361.5850 - val_loss: 263570096.0000 - val_mae: 11276.8945
Epoch 11/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 263855520.0000 - mae: 11757.7178 - val_loss: 240982112.0000 - val_mae: 10606.0576
Epoch 12/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 237212352.0000 - mae: 10966.4570 - val_loss: 213387248.0000 - val_mae: 9759.7715
Epoch 13/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 205972544.0000 - mae: 9986.0137 - val_loss: 181989488.0000 - val_mae: 8742.1006
Epoch 14/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 171376112.0000 - mae: 8847.4561 - val_loss: 148884704.0000 - val_mae: 7643.5449
Epoch 15/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 136496800.0000 - mae: 7628.3760 - val_loss: 117182864.0000 - val_mae: 6542.1694
Epoch 16/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 105166568.0000 - mae: 6459.8911 - val_loss: 89407840.0000 - val_mae: 5548.1450
Epoch 17/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 79841224.0000 - mae: 5514.3262 - val_loss: 68142312.0000 - val_mae: 4796.0674
Epoch 18/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 61341364.0000 - mae: 4834.5898 - val_loss: 54349352.0000 - val_mae: 4356.4961
Epoch 19/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 50105140.0000 - mae: 4475.3354 - val_loss: 45845952.0000 - val_mae: 4254.4087
Epoch 20/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 43928840.0000 - mae: 4420.2510 - val_loss: 41258868.0000 - val_mae: 4270.2271
Epoch 21/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 40811560.0000 - mae: 4462.3354 - val_loss: 38645892.0000 - val_mae: 4290.9785
Epoch 22/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 39087972.0000 - mae: 4484.6714 - val_loss: 37218928.0000 - val_mae: 4272.2715
Epoch 23/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 38003976.0000 - mae: 4447.3267 - val_loss: 36262624.0000 - val_mae: 4235.6284
Epoch 24/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 37325124.0000 - mae: 4416.3188 - val_loss: 35516028.0000 - val_mae: 4201.3936
Epoch 25/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 36855652.0000 - mae: 4393.3188 - val_loss: 34932812.0000 - val_mae: 4174.3457
Epoch 26/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 36450264.0000 - mae: 4352.0757 - val_loss: 34489704.0000 - val_mae: 4114.7139
Epoch 27/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 36138652.0000 - mae: 4300.4995 - val_loss: 34214868.0000 - val_mae: 4069.7461
Epoch 28/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 35921004.0000 - mae: 4265.6514 - val_loss: 34001052.0000 - val_mae: 4035.3376
Epoch 29/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 35737228.0000 - mae: 4241.8979 - val_loss: 33565276.0000 - val_mae: 4014.3125
Epoch 30/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 35553996.0000 - mae: 4221.8730 - val_loss: 33469216.0000 - val_mae: 3976.2664
Epoch 31/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 35403280.0000 - mae: 4179.4038 - val_loss: 33340126.0000 - val_mae: 3942.3184
Epoch 32/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 35255644.0000 - mae: 4153.3159 - val_loss: 33194174.0000 - val_mae: 3915.9014
Epoch 33/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 35183296.0000 - mae: 4139.8403 - val_loss: 33000482.0000 - val_mae: 3893.0894
Epoch 34/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 35055480.0000 - mae: 4123.8545 - val_loss: 32833422.0000 - val_mae: 3869.4033
Epoch 35/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 34947404.0000 - mae: 4093.4409 - val_loss: 32792686.0000 - val_mae: 3847.1174
Epoch 36/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 34879264.0000 - mae: 4084.0679 - val_loss: 32644768.0000 - val_mae: 3830.6426
Epoch 37/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 34789320.0000 - mae: 4066.7561 - val_loss: 32547000.0000 - val_mae: 3813.0474
Epoch 38/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 34708472.0000 - mae: 4056.1843 - val_loss: 32452994.0000 - val_mae: 3809.3167
Epoch 39/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 34632744.0000 - mae: 4040.8359 - val_loss: 32417340.0000 - val_mae: 3790.7690
Epoch 40/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 34629028.0000 - mae: 4043.8130 - val_loss: 32284716.0000 - val_mae: 3780.1550
Epoch 41/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 34500360.0000 - mae: 4011.9653 - val_loss: 32344596.0000 - val_mae: 3756.9031
Epoch 42/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 34399336.0000 - mae: 3998.3589 - val_loss: 32241428.0000 - val_mae: 3747.8540
Epoch 43/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 34347516.0000 - mae: 3996.8423 - val_loss: 32129398.0000 - val_mae: 3743.1145
Epoch 44/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 34293368.0000 - mae: 3991.9736 - val_loss: 32064866.0000 - val_mae: 3734.0923
Epoch 45/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 34210212.0000 - mae: 3974.2673 - val_loss: 32089588.0000 - val_mae: 3724.1909
Epoch 46/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 34170688.0000 - mae: 3974.6169 - val_loss: 31949004.0000 - val_mae: 3726.1833
Epoch 47/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 34108060.0000 - mae: 3963.2559 - val_loss: 32037026.0000 - val_mae: 3712.3977
Epoch 48/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 34037596.0000 - mae: 3944.1401 - val_loss: 32012232.0000 - val_mae: 3701.0000
Epoch 49/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 33953204.0000 - mae: 3949.1304 - val_loss: 31845574.0000 - val_mae: 3707.6765
Epoch 50/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 33938864.0000 - mae: 3947.0322 - val_loss: 31800258.0000 - val_mae: 3694.6975
Epoch 51/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 33846116.0000 - mae: 3926.7559 - val_loss: 31876616.0000 - val_mae: 3686.1462
Epoch 52/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 33788348.0000 - mae: 3917.6880 - val_loss: 31818316.0000 - val_mae: 3683.0220
Epoch 53/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 33710440.0000 - mae: 3922.8828 - val_loss: 31702758.0000 - val_mae: 3686.2732
Epoch 54/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 33690528.0000 - mae: 3913.6055 - val_loss: 31710004.0000 - val_mae: 3670.0820
Epoch 55/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 33627404.0000 - mae: 3915.5735 - val_loss: 31572858.0000 - val_mae: 3678.5388
Epoch 56/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 33530452.0000 - mae: 3905.7930 - val_loss: 31609038.0000 - val_mae: 3666.9497
Epoch 57/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 33485264.0000 - mae: 3893.7107 - val_loss: 31547596.0000 - val_mae: 3659.8286
Epoch 58/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 33404768.0000 - mae: 3887.4712 - val_loss: 31514110.0000 - val_mae: 3655.7913
Epoch 59/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 33384680.0000 - mae: 3880.6980 - val_loss: 31504578.0000 - val_mae: 3652.6057
Epoch 60/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 33314860.0000 - mae: 3887.3853 - val_loss: 31380978.0000 - val_mae: 3657.9102
Epoch 61/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 33231706.0000 - mae: 3881.8335 - val_loss: 31331604.0000 - val_mae: 3647.8687
Epoch 62/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 33197000.0000 - mae: 3869.0686 - val_loss: 31380076.0000 - val_mae: 3634.4224
Epoch 63/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 33108564.0000 - mae: 3852.5164 - val_loss: 31369728.0000 - val_mae: 3626.9202
Epoch 64/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 33056356.0000 - mae: 3849.9424 - val_loss: 31222976.0000 - val_mae: 3629.1321
Epoch 65/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 32989868.0000 - mae: 3842.8484 - val_loss: 31177968.0000 - val_mae: 3621.1663
Epoch 66/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 32897422.0000 - mae: 3842.1443 - val_loss: 31147966.0000 - val_mae: 3626.7273
Epoch 67/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 32938922.0000 - mae: 3851.4797 - val_loss: 31088154.0000 - val_mae: 3623.2947
Epoch 68/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 32773840.0000 - mae: 3827.0105 - val_loss: 31118402.0000 - val_mae: 3608.2302
Epoch 69/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 32722704.0000 - mae: 3821.9421 - val_loss: 31031708.0000 - val_mae: 3609.7915
Epoch 70/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 32645134.0000 - mae: 3817.9656 - val_loss: 31018376.0000 - val_mae: 3607.6084
Epoch 71/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 32584286.0000 - mae: 3812.9116 - val_loss: 30954562.0000 - val_mae: 3602.9766
Epoch 72/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 32536042.0000 - mae: 3812.6863 - val_loss: 30881026.0000 - val_mae: 3600.4617
Epoch 73/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 32463014.0000 - mae: 3802.7754 - val_loss: 30882464.0000 - val_mae: 3591.3186
Epoch 74/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 32395312.0000 - mae: 3794.9456 - val_loss: 30853400.0000 - val_mae: 3591.0566
Epoch 75/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 32309390.0000 - mae: 3788.7981 - val_loss: 30730460.0000 - val_mae: 3586.2690
Epoch 76/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 32257426.0000 - mae: 3788.8872 - val_loss: 30678318.0000 - val_mae: 3583.4810
Epoch 77/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 32216652.0000 - mae: 3782.5034 - val_loss: 30681174.0000 - val_mae: 3573.2559
Epoch 78/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 32108742.0000 - mae: 3768.4656 - val_loss: 30587048.0000 - val_mae: 3569.0645
Epoch 79/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 32095236.0000 - mae: 3770.7764 - val_loss: 30483652.0000 - val_mae: 3562.7468
Epoch 80/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 31968828.0000 - mae: 3752.6938 - val_loss: 30557406.0000 - val_mae: 3559.1553
Epoch 81/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 31961000.0000 - mae: 3736.9775 - val_loss: 30579138.0000 - val_mae: 3545.0940
Epoch 82/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 31860354.0000 - mae: 3740.1711 - val_loss: 30330140.0000 - val_mae: 3560.1616
Epoch 83/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 31784178.0000 - mae: 3744.0562 - val_loss: 30371124.0000 - val_mae: 3547.2441
Epoch 84/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 31820396.0000 - mae: 3724.5273 - val_loss: 30445286.0000 - val_mae: 3532.3740
Epoch 85/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 31911982.0000 - mae: 3758.9749 - val_loss: 30106354.0000 - val_mae: 3548.9221
Epoch 86/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 31567078.0000 - mae: 3721.7727 - val_loss: 30148704.0000 - val_mae: 3531.7859
Epoch 87/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 31505738.0000 - mae: 3702.4282 - val_loss: 30148684.0000 - val_mae: 3521.2112
Epoch 88/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 31492510.0000 - mae: 3697.2581 - val_loss: 30006870.0000 - val_mae: 3521.1643
Epoch 89/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 31413114.0000 - mae: 3701.9402 - val_loss: 29955780.0000 - val_mae: 3521.9373
Epoch 90/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 31312650.0000 - mae: 3698.2039 - val_loss: 29970334.0000 - val_mae: 3520.2673
Epoch 91/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - loss: 31252624.0000 - mae: 3701.5793 - val_loss: 29854664.0000 - val_mae: 3522.2498
Epoch 92/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 31147354.0000 - mae: 3674.5696 - val_loss: 29866714.0000 - val_mae: 3502.7866
Epoch 93/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 31088344.0000 - mae: 3662.0564 - val_loss: 29802622.0000 - val_mae: 3500.3730
Epoch 94/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - loss: 31000588.0000 - mae: 3669.8779 - val_loss: 29687048.0000 - val_mae: 3498.0515
Epoch 95/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 30977620.0000 - mae: 3652.9939 - val_loss: 29651220.0000 - val_mae: 3481.1306
Epoch 96/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 30885474.0000 - mae: 3663.6794 - val_loss: 29477226.0000 - val_mae: 3495.0601
Epoch 97/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 30785748.0000 - mae: 3653.3276 - val_loss: 29546464.0000 - val_mae: 3475.5300
Epoch 98/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 30713700.0000 - mae: 3629.7810 - val_loss: 29534174.0000 - val_mae: 3477.4629
Epoch 99/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 30665034.0000 - mae: 3627.9355 - val_loss: 29436090.0000 - val_mae: 3472.8142
Epoch 100/100
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 30621834.0000 - mae: 3659.4485 - val_loss: 29256790.0000 - val_mae: 3488.6299

In [15]:
loss, mae = model.evaluate(X_test, y_test)

print("Loss:", loss)

print("MAE:", mae)

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 28256508.0000 - mae: 3623.3435
Loss: 28256508.0
MAE: 3623.343505859375

In [16]:
predictions = model.predict(X_test)

9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step

In [17]:
mse = mean_squared_error(y_test, predictions)

rmse = np.sqrt(mse)

r2 = r2_score(y_test, predictions)

print("MSE :", mse)

print("RMSE :", rmse)

print("R2 Score :", r2)

MSE : 28256508.45838076
RMSE : 5315.685135368794
R2 Score : 0.8179920171529514

In [18]:
model.save("insurance_ann.keras")

print("Model Saved Successfully")

Model Saved Successfully

In [19]:
results = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": predictions.flatten()
})

results.to_csv("prediction_results.csv", index=False)

results.head()

        Actual     Predicted
0   9095.06825   9973.721680
1   5272.17580   5888.441895
2  29330.98315  36999.394531
3   9301.89355   8135.370605
4  33750.29180  27493.750000